# Generated by Django 3.2.8 on 2022-08-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0002_tips_tipid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='tip',
            new_name='tips',
        ),
    ]
