# Generated by Django 3.2.8 on 2022-08-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0003_rename_tip_tips_tips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='tipid',
            new_name='tipsid',
        ),
    ]
